# Generated by Django 4.1.3 on 2022-11-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax_rate',
            new_name='tax_rates',
        ),
    ]
