# Generated by Django 4.1.3 on 2022-11-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_tax_rate_order_tax_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_off', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='order', to='api.coupon'),
        ),
    ]
