# Generated by Django 4.1.3 on 2022-11-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coupon_order_coupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_currency', to='api.currency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_currency', to='api.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='currency_options',
            field=models.ManyToManyField(blank=True, through='api.OrderCurrency', to='api.currency'),
        ),
    ]
