# Generated by Django 4.1.3 on 2022-11-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_currency_ordercurrency_order_currency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_currency', to='api.currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_currency', to='api.item')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency_options',
        ),
        migrations.DeleteModel(
            name='OrderCurrency',
        ),
        migrations.AddField(
            model_name='item',
            name='currency_options',
            field=models.ManyToManyField(blank=True, through='api.ItemCurrency', to='api.currency'),
        ),
    ]
